server.port: 7002
server.error.include-message: always

logging:
  level:
    root: INFO
    se.kajzer: DEBUG

spring.data.mongodb:
  host: localhost
  port: 27017
  database: recommendation-db
  org.springframework.data.mongodb.core.MongoTemplate: DEBUG

---
spring.profiles: docker

spring.data.mongodb.host: mongodb

server.port: 8080