server.port: 7003
server.error.include-message: always

spring.data.mongodb:
  host: localhost
  port: 27017
  database: review-db

logging:
  level:
    root: INFO
    se.kajzer: DEBUG

---
spring.profiles: docker

spring.data.mongodb.host: mongodb

server.port: 8080